### ISSUE TITLE
关于负二项回归模型原理、方差推导

### ISSUE THREAD

**Issue by liuzl434869604** [MathAndAlgo/DiscussionBoard#9]
续[如何理解RNAseq counts数据符合负二项分布?](https://www.zhihu.com/question/66648588/answer/266215154) @shouldsee

1. (基本解决)那个你知乎里的EQ1怎么推到最后的方差呀还是不是很明白，我试着拼了个方差的期望，但是还是销不掉

我自己试着证明：
M_ij满足一个泊松-伽马混合分布：
M_ij~Poisson(μ_ij ),μ_ij~Gamma(a,b)
则给定μ_ij的分布时，
E(M_ij│μ_ij )=〖Var((M_ij│μ_ij )=μ〗_ij
E(μ_ij )=ab，Var(μ_ij )=ab^2
根据条件方差公式，   Var(M_ij )=Var(E(M_ij│μ_ij ))+E(Var((M_ij│μ_ij ))
         =Var(μ_ij )+ E(μ_ij )=ab+ ab^2
                                                               =bE(μ_ij )+ E(μ_ij )
又根据离散随机变量的期望的定义，
E(M_ij )=∑▒〖E(〗 M_ij |μ_ij )*P(μ_ij )=∑▒〖μ_ij*P(μ_ij ) 〗=E(μ_ij )

因此，                                    Var(M_ij )=bE(M_ij )+ E(M_ij )
=(b〖E(M_ij )〗^2)/E(M_ij ) + E(M_ij )

                                                                       =μ_ij+α〖μ_ij〗^2（想要推到这个结果）

2、陈强以及科林的教材，里面提到是  为解决过度离散，（如果按你知乎的符号）令Y=u*v，然后v才是符合伽马分布。你这里提到Y就是符合伽马分布，请问怎么理解？另外计算时候好像发现这两个分布的参数好像一样？？比较疑惑

λ_i=u_i*v_i(这里的λ_i 就是相当于条件方差里提到的X）
而v_i才是符合一个伽马分布，即v_i~GAMMA(1/α，α)，但你这里是假设整个λ_i=u_i*v_i符合一个伽马分布。

根据方差的结果，
Var(X)=E(x)+θ〖E(x)〗^2= E(x)+α〖E(x)〗^2(两个式子中，相当于θ=α，只是符号不一样而已)
代进去计算发现，貌似这两种伽马分布的参数是一样的？？？？

总得就是想问，这两种伽马分布如何理解？而且为什么带进去计算好像伽马分布的参数是一样的呀？

**Comment by liuzl434869604** [comment]
![image](https://user-images.githubusercontent.com/36130333/35778084-fa3f4a1c-09f3-11e8-8301-9819577b8f72.png)

**Comment by liuzl434869604** [comment]
[1.pdf](https://github.com/MathAndAlgo/DiscussionBoard/files/1692853/1.pdf)

**Comment by shouldsee** [comment]
已解决
